version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: warehouse-postgres
    environment:
      POSTGRES_DB: WareHouseDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_INITDB_ARGS: --auth md5
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - warehouse-network

  # Redis for cashing
  redis:
    image: redis:7-alpine
    container_name: warehouse-redis
    ports:
      - "6379:6379"
    networks:
      - warehouse-network

  # Zookeeper (for Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: warehouse-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - warehouse-network

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: warehouse-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - warehouse-network

  # PGAdmin for managing DB
  pgadmin:
    image: dpage/pgadmin4
    container_name: warehouse-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@warehouse.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - warehouse-network

volumes:
  postgres_data:

networks:
  warehouse-network:
    driver: bridge